services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: ADMIN_PASSWORD
        value: ${ADMIN_PASSWORD}
    healthCheckPath: /
    autoDeploy: true
    plan: free
