[server]
enableCORS = false
enableXsrfProtection = true
sslCertFile = ""
sslKeyFile = ""

[browser]
serverAddress = "nuanswers.onrender.com"
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif" 